export const COUNTRY_OPTIONS = [
  "Worldwide",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belgium",
  "Belarus",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Cambodia",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malaysia",
  "Malta",
  "Mauritius",
  "Mexico",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const REGION_OPTIONS: Record<string, string[]> = {
  Australia: ["New South Wales", "Queensland", "Victoria", "Western Australia"],
  Bangladesh: ["Chattogram", "Dhaka", "Khulna", "Rajshahi", "Sylhet"],
  Canada: ["Alberta", "British Columbia", "Ontario", "Quebec"],
  Denmark: ["Capital Region of Denmark", "Central Denmark Region", "North Denmark Region", "Region Zealand", "Region of Southern Denmark"],
  Germany: ["Bavaria", "Berlin", "Hamburg", "Hesse"],
  Iceland: ["Capital Region", "Northeastern Region", "Southern Peninsula", "Southern Region", "Western Region"],
  India: ["Delhi", "Karnataka", "Maharashtra", "Tamil Nadu"],
  Pakistan: ["Balochistan", "Islamabad Capital Territory", "Khyber Pakhtunkhwa", "Punjab", "Sindh"],
  "Saudi Arabia": ["Eastern Province", "Makkah", "Madinah", "Riyadh"],
  "United Arab Emirates": ["Abu Dhabi", "Dubai", "Sharjah"],
  "United Kingdom": ["England", "Northern Ireland", "Scotland", "Wales"],
  "United States": ["California", "Florida", "Illinois", "New York", "Texas", "Washington"]
};

export const CITY_OPTIONS: Record<string, string[]> = {
  "Australia|New South Wales": ["Sydney", "Newcastle", "Wollongong", "Parramatta"],
  "Australia|Queensland": ["Brisbane", "Gold Coast", "Sunshine Coast", "Townsville"],
  "Australia|Victoria": ["Melbourne", "Geelong", "Ballarat", "Bendigo"],
  "Australia|Western Australia": ["Perth", "Fremantle", "Bunbury"],
  "Bangladesh|Chattogram": ["Chattogram", "Cox's Bazar", "Comilla"],
  "Bangladesh|Dhaka": ["Dhaka", "Gazipur", "Narayanganj"],
  "Bangladesh|Khulna": ["Khulna", "Jessore", "Satkhira"],
  "Bangladesh|Rajshahi": ["Rajshahi", "Bogra", "Pabna"],
  "Bangladesh|Sylhet": ["Sylhet", "Moulvibazar", "Habiganj"],
  "Canada|Alberta": ["Calgary", "Edmonton", "Red Deer", "Lethbridge"],
  "Canada|British Columbia": ["Vancouver", "Victoria", "Burnaby", "Surrey"],
  "Canada|Ontario": ["Ottawa", "Toronto", "Mississauga", "Hamilton"],
  "Canada|Quebec": ["Montreal", "Quebec City", "Laval", "Gatineau"],
  "Denmark|Capital Region of Denmark": ["Copenhagen", "Hillerod", "Helsingor", "Frederiksberg"],
  "Denmark|Central Denmark Region": ["Aarhus", "Herning", "Randers", "Silkeborg"],
  "Denmark|North Denmark Region": ["Aalborg", "Hjorring", "Frederikshavn"],
  "Denmark|Region Zealand": ["Roskilde", "Naestved", "Koge", "Slagelse"],
  "Denmark|Region of Southern Denmark": ["Odense", "Esbjerg", "Kolding", "Vejle"],
  "Germany|Bavaria": ["Munich", "Nuremberg", "Augsburg", "Regensburg"],
  "Germany|Berlin": ["Berlin"],
  "Germany|Hamburg": ["Hamburg", "Altona", "Harburg"],
  "Germany|Hesse": ["Frankfurt", "Wiesbaden", "Darmstadt", "Kassel"],
  "Iceland|Capital Region": ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Gardabaer"],
  "Iceland|Northeastern Region": ["Akureyri", "Husavik", "Egilsstadir"],
  "Iceland|Southern Peninsula": ["Keflavik", "Reykjanesbaer", "Grindavik"],
  "Iceland|Southern Region": ["Selfoss", "Vik", "Hveragerdi"],
  "Iceland|Western Region": ["Akranes", "Borgarnes", "Stykkisholmur"],
  "India|Delhi": ["New Delhi", "Delhi", "Noida", "Gurugram"],
  "India|Karnataka": ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi"],
  "India|Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik"],
  "India|Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli"],
  "Pakistan|Balochistan": ["Gwadar", "Quetta", "Khuzdar", "Turbat"],
  "Pakistan|Islamabad Capital Territory": ["Islamabad"],
  "Pakistan|Khyber Pakhtunkhwa": ["Abbottabad", "Mardan", "Peshawar", "Swat", "Kohat", "Mansehra"],
  "Pakistan|Punjab": ["Bahawalpur", "Faisalabad", "Gujranwala", "Gujrat", "Lahore", "Multan", "Rawalpindi", "Sahiwal", "Sargodha", "Sheikhupura", "Sialkot"],
  "Pakistan|Sindh": ["Hyderabad", "Karachi", "Larkana", "Mirpur Khas", "Nawabshah", "Sukkur", "Thatta"],
  "Saudi Arabia|Eastern Province": ["Dammam", "Dhahran", "Khobar"],
  "Saudi Arabia|Makkah": ["Jeddah", "Makkah", "Taif"],
  "Saudi Arabia|Madinah": ["Madinah", "Yanbu"],
  "Saudi Arabia|Riyadh": ["Riyadh", "Al Kharj"],
  "United Arab Emirates|Abu Dhabi": ["Abu Dhabi", "Al Ain", "Madinat Zayed"],
  "United Arab Emirates|Dubai": ["Dubai", "Jebel Ali"],
  "United Arab Emirates|Sharjah": ["Sharjah", "Khor Fakkan"],
  "United Kingdom|England": ["London", "Manchester", "Birmingham", "Leeds"],
  "United Kingdom|Northern Ireland": ["Belfast", "Derry", "Lisburn"],
  "United Kingdom|Scotland": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"],
  "United Kingdom|Wales": ["Cardiff", "Swansea", "Newport"],
  "United States|California": ["Los Angeles", "San Francisco", "San Diego", "San Jose"],
  "United States|Florida": ["Miami", "Orlando", "Tampa", "Jacksonville"],
  "United States|Illinois": ["Chicago", "Springfield", "Naperville"],
  "United States|New York": ["New York City", "Buffalo", "Albany", "Rochester"],
  "United States|Texas": ["Austin", "Dallas", "Houston", "San Antonio"],
  "United States|Washington": ["Seattle", "Spokane", "Tacoma", "Bellevue"]
};

export function getRegionOptions(country?: string) {
  return REGION_OPTIONS[country ?? ""] ?? [];
}

export function getCityOptions(country?: string, region?: string) {
  if (!country || !region) {
    return [];
  }

  return CITY_OPTIONS[`${country}|${region}`] ?? [];
}
